# API Configuration shared amongst profiles
voyager.path.airports=/airports
voyager.admin.airports=/admin/airports
voyager.path.iata=/iata
voyager.path.health=/actuator/health
voyager.path.airport-airlines=/airlines
voyager.path.nearby-airports=/nearby-airports
voyager.auth.token=${VOYAGER_AUTH_TOKEN}
voyager.admin.token=${ADMIN_AUTH_TOKEN}
voyager.test.token=${TEST_AUTH_TOKEN}
voyager.url=${VOYAGER_URL}